apiVersion: v1
kind: Service
metadata:
  name: serving-agent-service
spec:
  selector:
    app: serving-agent
  ports:
    - name: service
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
